service:
  32988-CLUCKY:  # 游戏服务
    service_id: "32988-CLUCKY"
    short_code: "32988"
    keyword: "CLUCKY"
    aoc_url: "http://203.223.130.34/aoc/api.php?telcoid=2&keywordid=3237"
    service_name: "GAME"
    price: "10"
    country: "MALAI"
    limit_sub_num: 2000
    camp_id: 2
  32988-PLAY:  # 游戏服务
    service_id: "32988-PLAY"
    short_code: "32988"
    keyword: "PLAY"
    aoc_url: "http://203.223.130.34/aoc/api.php?telcoid=2&keywordid=4321"
    service_name: "GAME"
    price: "10"
    country: "MALAI"
    limit_sub_num: 2000
    camp_id: 2
